# -*- coding: utf-8 -*-
"""DL_yolo_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nGAlwH_Ji1kV4j0KQl_queD9KYpEORdD

Connect to drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""Finding dataset"""

from google.colab import drive
import os, glob

# Mount your drive
drive.mount('/content/drive')

# Path to the folder inside your Google Drive (must be added to "My Drive")
DATASET_ROOT = "/content/drive/MyDrive/Celebrity Image Subsets"

# Verify
if not os.path.exists(DATASET_ROOT):
    raise FileNotFoundError(f"❌ Dataset not found at {DATASET_ROOT}. Check if you added the shared folder to My Drive!")

print("✅ Dataset folder found:", DATASET_ROOT)

"""Extracting data"""

celebrity_folders = [f for f in os.listdir(DATASET_ROOT) if f.startswith("images_")]
print(f"[INFO] Found {len(celebrity_folders)} celebrity folders.")

all_images, all_labels = [], []

for folder in celebrity_folders:
    folder_path = os.path.join(DATASET_ROOT, folder)
    image_files = glob.glob(os.path.join(folder_path, "*.jpg"))

    celeb_id = folder.split("_")[1]  # extract ID
    for img_path in image_files:
        all_images.append(img_path)
        all_labels.append(celeb_id)

print(f"[INFO] Total images collected: {len(all_images)}")
print(f"[INFO] Unique celeb IDs: {len(set(all_labels))}")
print("Example:", all_images[0], "-> celeb ID:", all_labels[0])

"""Creating subfolder"""

import os

# Root dataset path
YOLO_DATASET_ROOT = "/content/datasets/group_celeb"

# Subfolders for YOLOv8 dataset
splits = ["train", "val", "test"]
for split in splits:
    os.makedirs(os.path.join(YOLO_DATASET_ROOT, "images", split), exist_ok=True)
    os.makedirs(os.path.join(YOLO_DATASET_ROOT, "labels", split), exist_ok=True)

print(f"[INFO] YOLO dataset structure created at {YOLO_DATASET_ROOT}")
for root, dirs, files in os.walk(YOLO_DATASET_ROOT):
    level = root.replace(YOLO_DATASET_ROOT, '').count(os.sep)
    indent = ' ' * 2 * level
    print(f"{indent}{os.path.basename(root)}/")
    subindent = ' ' * 2 * (level + 1)
    for f in files:
        print(f"{subindent}{f}")

"""concatinating and splliting data into test , train, val"""

import os, cv2, random, numpy as np
from glob import glob
from tqdm import tqdm
from PIL import Image
from torchvision import transforms

# === CONFIGURATION ===
CELEB_ROOT = "/content/drive/MyDrive/Celebrity Image Subsets"
YOLO_DATASET_ROOT = "/content/datasets/group_celeb"
CANVAS_SIZE = (1280, 720)   # width x height
FACE_SIZE = (128, 128)      # smaller faces so more fit
TOTAL_IMAGES = 10000
MIN_FACES = 5
MAX_FACES = 40
OVERLAP_TOLERANCE = 0.05    # allow up to 5% overlap between faces

# Collect celeb folders
celeb_folders = [f for f in glob(os.path.join(CELEB_ROOT, "images_*")) if os.path.isdir(f)]
print(f"[INFO] Found {len(celeb_folders)} celebrity folders.")

# Augmentation pipeline
augment = transforms.Compose([
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.3),
    transforms.RandomRotation(degrees=15),
])

def random_augment(image):
    image = Image.fromarray(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    image = augment(image)
    return cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)

# Helper: placement with overlap tolerance
def get_random_position(existing_boxes, w, h, face_w, face_h, max_tries=50):
    for _ in range(max_tries):
        x = random.randint(0, w - face_w)
        y = random.randint(0, h - face_h)
        new_box = [x, y, x + face_w, y + face_h]
        overlap = False
        for (x1, y1, x2, y2) in existing_boxes:
            # Calculate intersection
            inter_x1 = max(x1, new_box[0])
            inter_y1 = max(y1, new_box[1])
            inter_x2 = min(x2, new_box[2])
            inter_y2 = min(y2, new_box[3])
            if inter_x1 < inter_x2 and inter_y1 < inter_y2:
                inter_area = (inter_x2 - inter_x1) * (inter_y2 - inter_y1)
                box_area = face_w * face_h
                if inter_area / box_area > OVERLAP_TOLERANCE:
                    overlap = True
                    break
        if not overlap:
            return new_box
    return None

# Split ratios
train_ratio, val_ratio, test_ratio = 0.8, 0.1, 0.1

for i in tqdm(range(TOTAL_IMAGES), desc="Generating synthetic dataset"):
    # Decide dataset split
    if i < int(TOTAL_IMAGES * train_ratio):
        split = "train"
    elif i < int(TOTAL_IMAGES * (train_ratio + val_ratio)):
        split = "val"
    else:
        split = "test"

    img_dir = os.path.join(YOLO_DATASET_ROOT, "images", split)
    label_dir = os.path.join(YOLO_DATASET_ROOT, "labels", split)

    # Blank canvas
    canvas = np.ones((CANVAS_SIZE[1], CANVAS_SIZE[0], 3), dtype=np.uint8) * 255
    label_lines, boxes = [], []

    selected_folders = random.sample(celeb_folders, random.randint(MIN_FACES, MAX_FACES))

    for folder in selected_folders:
        celeb_id = folder.split("_")[-1]  # e.g. images_<228> -> <228>
        image_paths = glob(os.path.join(folder, "*.jpg"))
        if not image_paths:
            continue
        face = cv2.imread(random.choice(image_paths))
        if face is None:
            continue
        face = random_augment(face)
        face = cv2.resize(face, FACE_SIZE)

        box = get_random_position(boxes, CANVAS_SIZE[0], CANVAS_SIZE[1], FACE_SIZE[0], FACE_SIZE[1])
        if box is None:
            continue
        x1, y1, x2, y2 = box
        boxes.append(box)
        canvas[y1:y2, x1:x2] = face

        # YOLO format (class x_center y_center w h)
        x_center = ((x1 + x2) / 2) / CANVAS_SIZE[0]
        y_center = ((y1 + y2) / 2) / CANVAS_SIZE[1]
        w_norm = FACE_SIZE[0] / CANVAS_SIZE[0]
        h_norm = FACE_SIZE[1] / CANVAS_SIZE[1]
        label_lines.append(f"{celeb_id} {x_center:.6f} {y_center:.6f} {w_norm:.6f} {h_norm:.6f}")

    # Save image + labels
    img_name = f"group_{i:05d}.jpg"
    label_name = f"group_{i:05d}.txt"
    cv2.imwrite(os.path.join(img_dir, img_name), canvas)
    with open(os.path.join(label_dir, label_name), "w") as f:
        f.write("\n".join(label_lines))

print(f"[INFO] Generated {TOTAL_IMAGES} group images with face size {FACE_SIZE} and mild overlap tolerance.")

!pip install ultralytics

!unzip group_celeb_dataset.zip -d /content/datasets/

"""creating yaml files"""

import yaml
import os

# Correct dataset root
YOLO_DATASET_ROOT = "/content/datasets/content/datasets/group_celeb"
yaml_path = "/content/group_celeb.yaml"

# Verify dataset structure
required_folders = [
    os.path.join(YOLO_DATASET_ROOT, "images/train"),
    os.path.join(YOLO_DATASET_ROOT, "images/val"),
    os.path.join(YOLO_DATASET_ROOT, "images/test"),
]
for p in required_folders:
    if not os.path.exists(p):
        raise FileNotFoundError(f"Missing required folder: {p}")

# Collect class IDs from label files
label_dir = os.path.join(YOLO_DATASET_ROOT, "labels/train")
class_ids = set()

for file in os.listdir(label_dir):
    if file.endswith(".txt"):
        with open(os.path.join(label_dir, file)) as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) > 0:
                    class_ids.add(parts[0])

class_ids = sorted(list(class_ids))
print(f"[INFO] Found {len(class_ids)} unique celeb IDs")

# Create YAML dictionary
data_config = {
    "path": YOLO_DATASET_ROOT,
    "train": "images/train",
    "val": "images/val",
    "test": "images/test",
    "names": {i: cid for i, cid in enumerate(class_ids)},
    "nc": len(class_ids),
}

# Save YAML file
with open(yaml_path, "w") as f:
    yaml.dump(data_config, f, default_flow_style=False)

print(f"[INFO] YOLO data.yaml created at {yaml_path}")
print(f"[INFO] Number of classes: {len(class_ids)}")

"""formatting the labels"""

import os
from tqdm import tqdm

# Root path
LABEL_ROOT = "/content/datasets/content/datasets/group_celeb/labels"
yaml_path = "/content/group_celeb.yaml"

# Collect all class IDs
class_ids = set()
for split in ["train", "val", "test"]:
    label_dir = os.path.join(LABEL_ROOT, split)
    for file in os.listdir(label_dir):
        if file.endswith(".txt"):
            with open(os.path.join(label_dir, file)) as f:
                for line in f:
                    parts = line.strip().split()
                    if len(parts) > 0:
                        class_ids.add(parts[0])

class_ids = sorted(list(class_ids))
id_to_index = {cid: i for i, cid in enumerate(class_ids)}

print(f"[INFO] Found {len(class_ids)} unique celeb IDs.")
print(f"[INFO] Example mapping: {list(id_to_index.items())[:5]}")

# Rewrite label files with numeric IDs
for split in ["train", "val", "test"]:
    label_dir = os.path.join(LABEL_ROOT, split)
    for file in tqdm(os.listdir(label_dir), desc=f"Fixing {split} labels"):
        if not file.endswith(".txt"):
            continue
        lines_out = []
        with open(os.path.join(label_dir, file)) as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) != 5:
                    continue
                old_id = parts[0]
                if old_id not in id_to_index:
                    continue
                new_id = id_to_index[old_id]
                lines_out.append(f"{new_id} {' '.join(parts[1:])}")
        with open(os.path.join(label_dir, file), "w") as f:
            f.write("\n".join(lines_out))

print("[INFO] All label files updated with numeric class IDs.")

# Rewrite YAML
import yaml

data_config = {
    "path": "/content/datasets/content/datasets/group_celeb",
    "train": "images/train",
    "val": "images/val",
    "test": "images/test",
    "names": {i: cid for i, cid in enumerate(class_ids)},
    "nc": len(class_ids),
}

with open(yaml_path, "w") as f:
    yaml.dump(data_config, f, default_flow_style=False)

print(f"[INFO] YAML file rewritten at {yaml_path}")

!nvidia-smi

"""training the model"""

from ultralytics import YOLO

model = YOLO("yolov8n.pt")
model.train(
    data="/content/group_celeb.yaml",
    epochs=25,
    imgsz=640,
    batch=16,
    workers=2,
    device=0
)

import os

def show_folder_structure(root_dir, max_depth=4):
    """
    Recursively prints folder structure starting from root_dir.
    Limits recursion to max_depth for readability.
    """
    for root, dirs, files in os.walk(root_dir):
        depth = root.replace(root_dir, "").count(os.sep)
        if depth >= max_depth:
            continue
        indent = " " * 2 * depth
        print(f"{indent}{os.path.basename(root)}/")
        subindent = " " * 2 * (depth + 1)
        for f in files:
            print(f"{subindent}{f}")

# Example: show structure from your dataset root
show_folder_structure("/content", max_depth=5)

"""moving the model to location

"""

!cp /content/runs/detect/train/weights/best.pt /content/best_face_yolo.pt
print("✅ Model copied to /content/best_face_yolo.pt")

"""downloding the model"""

from google.colab import files
files.download("/content/best_face_yolo.pt")

"""testing with an image"""

from ultralytics import YOLO
from IPython.display import Image, display
import glob

# Load trained model
model = YOLO("/content/best_face_yolo.pt")

# Run detection on test images
results = model.predict(
    source="/content/datasets/content/datasets/group_celeb/images/test",
    conf=0.5,
    save=True
)

# Display some outputs
detected_images = glob.glob(f"{results[0].save_dir}/*.jpg")
print(f"[INFO] Showing {len(detected_images)} detected images:")
for img_path in detected_images[:5]:
    display(Image(filename=img_path))