# -*- coding: utf-8 -*-
"""Milestone2_IE6150_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QVC0cFt9tviZq71f2hObWZ-xA0gc6en-
"""

!pip install ultralytics

# rm -rf /content/runs/detect

from google.colab import drive
drive.mount('/content/drive')

import os
import cv2
import numpy as np
import random
from pathlib import Path
import shutil
import albumentations as A
from ultralytics import YOLO
import yaml
import pickle
from google.colab import drive
import zipfile
import re
from collections import defaultdict
import pandas as pd
import matplotlib.pyplot as plt
from ultralytics import YOLO

"""##1.Data Extraction"""

# STEP 3: Mount Google Drive
print("Mounting Google Drive...")
drive.mount('/content/drive', force_remount=False)
print("✓ Google Drive mounted successfully\n")

DRIVE_ROOT = "/content/drive/MyDrive/celebA"
ZIP_FILE = "/content/drive/MyDrive/celebA/Archive.zip"
EXTRACTED_DIR = f"{DRIVE_ROOT}/extracted_images"
OUTPUT_ROOT = f"{DRIVE_ROOT}/output"

def extract_and_organize_zip(zip_path, extract_to, num_classes, celebrity_mapping=None, images_per_celebrity=None):
    """Extract and organize images by celebrity ID"""
    print(f"\nExtracting and organizing zip file...")
    print(f"Source: {zip_path}")
    print(f"Destination: {extract_to}")

    extract_path = Path(extract_to)
    extract_path.mkdir(parents=True, exist_ok=True)

    zip_source = Path(zip_path)

    # Handle different cases
    if zip_source.is_dir():
        print(f"Source is a directory, searching for .zip files...")
        zip_files = list(zip_source.glob('*.zip'))
        if not zip_files:
            print(f"No .zip files found, checking for images...")
            temp_extract = zip_source
        else:
            zip_file = zip_files[0]
            print(f"Found zip file: {zip_file}")
            temp_extract = extract_path / "temp_extract"
            temp_extract.mkdir(exist_ok=True)

            print("Extracting zip file...")
            with zipfile.ZipFile(zip_file, 'r') as zip_ref:
                zip_ref.extractall(temp_extract)
            print("✓ Zip file extracted")
    elif zip_source.suffix == '.zip':
        print(f"Extracting zip file: {zip_source}")
        temp_extract = extract_path / "temp_extract"
        temp_extract.mkdir(exist_ok=True)

        with zipfile.ZipFile(zip_source, 'r') as zip_ref:
            zip_ref.extractall(temp_extract)
        print("✓ Zip file extracted")
    else:
        print(f"Error: {zip_path} is neither a directory nor a .zip file")
        return None, {}, {}

    # NEW: Pattern to extract celebrity ID from folder name
    folder_pattern = re.compile(r'images__(\d+)_')

    # NEW: Check if already organized in folders
    existing_folders = [d for d in temp_extract.iterdir() if d.is_dir() and folder_pattern.match(d.name)]

    if existing_folders:
        # Images are already organized in folders
        print("\nImages already organized in folders, preserving structure...")
        celebrity_counts = defaultdict(int)
        celebrity_names = {}  # NEW: Map ID to folder name

        for folder in existing_folders:
            match = folder_pattern.match(folder.name)
            if match:
                celebrity_id = match.group(1)
                celebrity_names[int(celebrity_id)] = folder.name  # Store folder name

                # Create output directory with celebrity ID
                celeb_dir = extract_path / celebrity_id
                celeb_dir.mkdir(exist_ok=True)

                # Copy all images from this folder
                images = []
                for ext in ['*.jpg', '*.jpeg', '*.png', '*.JPG', '*.JPEG', '*.PNG']:
                    images.extend(folder.glob(ext))

                for img_file in images:
                    if not img_file.name.startswith('._'):
                        dest_path = celeb_dir / img_file.name
                        shutil.copy2(img_file, dest_path)
                        celebrity_counts[celebrity_id] += 1

        organized_count = sum(celebrity_counts.values())
    else:
        # Images are loose, need to organize
        print("\nFinding image files...")
        image_files = []
        for ext in ['*.jpg', '*.jpeg', '*.png', '*.JPG', '*.JPEG', '*.PNG']:
            image_files.extend(temp_extract.rglob(ext))

        image_files = [f for f in image_files if not f.name.startswith('._')]
        image_files = sorted(image_files)

        print(f"Found {len(image_files)} image files")

        if len(image_files) == 0:
            print("Error: No images found!")
            return None, {}, {}

        # Pattern to match: images__celebrityID_*
        pattern = re.compile(r'images__(\d+)_')

        celebrity_counts = defaultdict(int)
        celebrity_names = {}  # NEW: Map ID to extracted name
        organized_count = 0

        print("\nOrganizing images...")
        for idx, img_file in enumerate(image_files):
            filename = img_file.name
            match = pattern.match(filename)

            if match:
                celebrity_id = match.group(1)
                # NEW: Extract full folder name pattern from filename
                folder_name_match = re.match(r'(images__\d+_)', filename)
                if folder_name_match and int(celebrity_id) not in celebrity_names:
                    celebrity_names[int(celebrity_id)] = folder_name_match.group(1).rstrip('_')
            elif celebrity_mapping and filename in celebrity_mapping:
                celebrity_id = str(celebrity_mapping[filename])
            elif images_per_celebrity:
                celebrity_id = str(idx // images_per_celebrity)
            else:
                celebrity_id = str(idx % num_classes)

            celeb_dir = extract_path / celebrity_id
            celeb_dir.mkdir(exist_ok=True)

            dest_path = celeb_dir / filename
            try:
                shutil.copy2(img_file, dest_path)
                celebrity_counts[celebrity_id] += 1
                organized_count += 1

                if organized_count % 100 == 0:
                    print(f"Progress: {organized_count}/{len(image_files)} images...")
            except Exception as e:
                print(f"Error copying {filename}: {e}")

    # Clean up temp folder
    if temp_extract != zip_source and temp_extract.exists() and str(temp_extract).endswith('temp_extract'):
        shutil.rmtree(temp_extract)

    print(f"\n✓ Successfully organized {organized_count} images")
    print(f"✓ Found {len(celebrity_counts)} celebrity classes")

    # Print summary
    print("\nCelebrity ID distribution:")
    print("-" * 50)
    for celeb_id in sorted(celebrity_counts.keys(), key=lambda x: int(x))[:10]:
        folder_name = celebrity_names.get(int(celeb_id), f"Celebrity {celeb_id}")
        print(f"{folder_name}: {celebrity_counts[celeb_id]} images")
    if len(celebrity_counts) > 10:
        print(f"... and {len(celebrity_counts) - 10} more classes")

    if celebrity_counts:
        max_celeb_id = max([int(cid) for cid in celebrity_counts.keys()])
        if max_celeb_id + 1 > num_classes:
            num_classes = max_celeb_id + 1

    return extract_path, celebrity_counts, celebrity_names  # NEW: Return celebrity names mapping

#organized_dir, celebrity_counts = extract_and_organize_zip(zip_path = ZIP_FILE , num_classes=43,extract_to = EXTRACTED_DIR, celebrity_mapping=None, images_per_celebrity=None)

organized_dir, celebrity_counts, celebrity_names = extract_and_organize_zip(
    zip_path=ZIP_FILE,
    num_classes=44,
    extract_to=EXTRACTED_DIR,
    celebrity_mapping=None,
    images_per_celebrity=None
)

"""##2.MultiCelebConcatinate"""

class CelebAYOLOProcessor:
    def __init__(self, celeba_root, output_root, num_classes):
        """Initialize the processor"""
        self.celeba_root = Path(celeba_root)
        self.output_root = Path(output_root)
        self.num_classes = num_classes
        self.img_size = 640
        self.output_root.mkdir(parents=True, exist_ok=True)


    def _resize_with_padding(self, img, target_size):
        """Resize image maintaining aspect ratio with padding"""
        h, w = img.shape[:2]
        scale = min(target_size/h, target_size/w)
        new_h, new_w = int(h*scale), int(w*scale)

        resized = cv2.resize(img, (new_w, new_h))

        padded = np.zeros((target_size, target_size, 3), dtype=np.uint8)
        y_offset = (target_size - new_h) // 2
        x_offset = (target_size - new_w) // 2
        padded[y_offset:y_offset+new_h, x_offset:x_offset+new_w] = resized

        return padded

    def step1_resize_images(self, input_dir, output_dir):
        """Resize all images to 640x640"""
        print(f"\nStep 1: Resizing images to {self.img_size}x{self.img_size}")

        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        input_path = Path(input_dir)
        celeb_dirs = [d for d in input_path.iterdir() if d.is_dir()]

        total_processed = 0

        for class_dir in sorted(celeb_dirs):
            class_id = class_dir.name
            output_class_dir = output_path / class_id
            output_class_dir.mkdir(parents=True, exist_ok=True)

            images = []
            for ext in ['*.jpg', '*.jpeg', '*.png', '*.JPG', '*.JPEG', '*.PNG']:
                images.extend(class_dir.glob(ext))

            if not images:
                continue

            for img_file in images:
                try:
                    img = cv2.imread(str(img_file))
                    if img is None:
                        continue

                    resized = self._resize_with_padding(img, self.img_size)
                    output_file = output_class_dir / img_file.name
                    cv2.imwrite(str(output_file), resized)
                    total_processed += 1

                    if total_processed % 100 == 0:
                        print(f"Progress: {total_processed} images...")
                except Exception as e:
                    print(f"Error: {e}")

        print(f"✓ Resized {total_processed} images")
        return total_processed

    def _create_single_composite(self, class_images, n_celebs):
        """Create a single composite image with n celebrities"""
        canvas_size = self.img_size
        # Custom grid layouts for better arrangements
        if n_celebs == 4:
            grid_rows, grid_cols = 2, 2
        elif n_celebs == 6:
            grid_rows, grid_cols = 2, 3
        elif n_celebs == 10:
            grid_rows, grid_cols = 2, 5  # 2x5 grid for 10 celebrities
        else:
            # Default: square-ish grid
            grid_size = int(np.ceil(np.sqrt(n_celebs)))
            grid_rows, grid_cols = grid_size, grid_size

        # Calculate canvas dimensions based on grid
        cell_width = canvas_size // grid_cols
        cell_height = canvas_size // grid_rows

        # Adjust canvas to fit grid exactly (no black bars)
        canvas_width = cell_width * grid_cols
        canvas_height = cell_height * grid_rows

        composite = np.ones((canvas_size, canvas_size, 3), dtype=np.uint8) * 255

        selected_classes = random.sample(list(class_images.keys()),
                                        min(n_celebs, len(class_images)))

        grid_size = int(np.ceil(np.sqrt(n_celebs)))
        cell_size = canvas_size // grid_size

        annotations = []

        for i, class_id in enumerate(selected_classes):
            img_path = random.choice(class_images[class_id])
            img = cv2.imread(str(img_path))

            if img is None:
                continue

            row = i // grid_size
            col = i % grid_size

            padding = 0  # No padding
            target_size = cell_size - 2*padding

            # Ensure target_size is positive
            if target_size <= 0:
                continue

            img_resized = cv2.resize(img, (target_size, target_size))

            y_start = row * cell_size + padding
            x_start = col * cell_size + padding
            y_end = y_start + target_size
            x_end = x_start + target_size

            composite[y_start:y_end, x_start:x_end] = img_resized

            # Calculate normalized coordinates (0-1 range)
            x_center = ((x_start + x_end) / 2) / canvas_size
            y_center = ((y_start + y_end) / 2) / canvas_size
            width = target_size / canvas_size
            height = target_size / canvas_size

            # Ensure all values are valid (between 0 and 1)
            if 0 < x_center < 1 and 0 < y_center < 1 and 0 < width < 1 and 0 < height < 1:
                annotations.append({
                    'class_id': int(class_id),
                    'x_center': float(x_center),
                    'y_center': float(y_center),
                    'width': float(width),
                    'height': float(height)
                })

        return composite, annotations

    def _save_yolo_annotations(self, filepath, annotations):
        """Save annotations in YOLO format"""
        with open(filepath, 'w') as f:
            for ann in annotations:
                class_id = int(ann['class_id'])
                f.write(f"{class_id} {ann['x_center']:.6f} "
                       f"{ann['y_center']:.6f} {ann['width']:.6f} "
                       f"{ann['height']:.6f}\n")

    def step3_create_composite_images(self, resized_dir, configs):
        """Create composite images with N celebrities per image"""
        print("\nStep 3: Creating composite images")

        class_images = {}
        resized_path = Path(resized_dir)
        celeb_dirs = [d for d in resized_path.iterdir() if d.is_dir()]

        for class_dir in celeb_dirs:
            class_id = int(class_dir.name)
            images = []
            for ext in ['*.jpg', '*.jpeg', '*.png']:
                images.extend(class_dir.glob(ext))
            if images:
                class_images[class_id] = images

        print(f"Total celebrities with images: {len(class_images)}")

        if len(class_images) < max(configs):
            configs = [c for c in configs if c <= len(class_images)]

        results = {}

        for n_celebs in configs:
            print(f"\nCreating composites with {n_celebs} celebrities...")
            config_dir = self.output_root / f"composite_{n_celebs}"
            config_dir.mkdir(parents=True, exist_ok=True)

            num_composites = min(1000, len(class_images) * 5)
            valid_composites = 0
            attempts = 0
            max_attempts = num_composites * 2

            while valid_composites < num_composites and attempts < max_attempts:
                composite, annotations = self._create_single_composite(class_images, n_celebs)

                if len(annotations) > 0:
                    img_name = f"composite_{valid_composites:05d}.jpg"
                    cv2.imwrite(str(config_dir / img_name), composite)

                    ann_name = f"composite_{valid_composites:05d}.txt"
                    self._save_yolo_annotations(config_dir / ann_name, annotations)

                    valid_composites += 1

                    if valid_composites % 100 == 0:
                        print(f"Created {valid_composites}/{num_composites} valid composites...")

                attempts += 1

            results[n_celebs] = config_dir
            print(f"✓ Created {valid_composites} valid composite images")

        return results


    def _read_yolo_annotations(self, label_path):
        """Read YOLO format annotations"""
        bboxes = []
        class_labels = []

        with open(label_path, 'r') as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) == 5:
                    class_id = int(float(parts[0]))
                    bbox = [float(x) for x in parts[1:]]
                    bboxes.append(bbox)
                    class_labels.append(class_id)

        return bboxes, class_labels

    def _write_yolo_annotations(self, label_path, bboxes, class_labels):
        """Write YOLO format annotations"""
        with open(label_path, 'w') as f:
            for bbox, class_id in zip(bboxes, class_labels):
                class_id = int(class_id)
                f.write(f"{class_id} {bbox[0]:.6f} {bbox[1]:.6f} "
                       f"{bbox[2]:.6f} {bbox[3]:.6f}\n")



# Initialize processor
processor = CelebAYOLOProcessor(
    celeba_root=EXTRACTED_DIR,
    output_root=OUTPUT_ROOT,
    num_classes=44
)

# STEP 1: Resize images
print("\n" + "="*70)
print("STEP 1: Resizing Images")
print("="*70)

resized_dir = f"{OUTPUT_ROOT}/resized"
total_resized = processor.step1_resize_images(
    input_dir=str(organized_dir),
    output_dir=resized_dir
)

# STEP 3: Create composites
print("\n" + "="*70)
print("STEP 3: Creating Composite Images")
print("="*70)

composite_dirs = processor.step3_create_composite_images(
    resized_dir=resized_dir,
    # configs=[4, 6, 10]  # Create composites with 4, 6, and 10 celebrities
    configs=[10]
)

# Display sample composite images for each configuration
print("\n" + "="*70)
print("Generated Sample Composite Images")
print("="*70)

for n_celebs, composite_dir in composite_dirs.items():
    print(f"\n{n_celebs} celebrities per image:")
    print(f"  Location: {composite_dir}")
    print(f"  Sample images: composite_00000.jpg to composite_00999.jpg")
    print(f"  Annotations: composite_00000.txt to composite_00999.txt")

    # Display info about first composite
    first_img = composite_dir / "composite_00000.jpg"
    first_ann = composite_dir / "composite_00000.txt"

    if first_img.exists() and first_ann.exists():
        with open(first_ann, 'r') as f:
            num_boxes = len(f.readlines())
        print(f"  ✓ First composite has {num_boxes} bounding boxes")

print("\n" + "="*70)
print("You can view these composite images in:")
print(f"{OUTPUT_ROOT}/composite_4/")
print(f"{OUTPUT_ROOT}/composite_6/")
print(f"{OUTPUT_ROOT}/composite_10/")
print("="*70)

# Ask user if they want to continue with training
print("\n" + "="*70)
print("CHECKPOINT: Composite images have been generated!")
print("="*70)
print("You can now:")
print("1. Check the generated composite images in Google Drive")
print("2. Continue with training (will take 1-2 hours)")
print("\nTo continue with training, the script will proceed automatically...")
print("To stop here, interrupt the cell now.")
print("="*70)

"""##3.Model Loading"""

MODEL_SAVE_DIR = f"{DRIVE_ROOT}/models"

class TrainCelebAYOLO:
    def __init__(self, celeba_root, output_root, num_classes=44):
        """Initialize YOLO training pipeline for CelebA composites"""
        self.celeba_root = Path(celeba_root)
        self.output_root = Path(output_root)
        self.num_classes = num_classes
        self.img_size = 640
        self.celeb_id_to_index = {}  # will be filled later
        self.output_root.mkdir(parents=True, exist_ok=True)

    # =========================================================================
    # STEP 4: Split dataset
    # =========================================================================
    def step4_split_dataset(self, composite_dir, train_ratio=0.8):
        """Split composite images into train/val sets"""
        print("\nStep 4: Splitting into train/val sets")

        dataset_dir = self.output_root / "yolo_dataset"
        train_img_dir = dataset_dir / "images" / "train"
        val_img_dir = dataset_dir / "images" / "val"
        train_label_dir = dataset_dir / "labels" / "train"
        val_label_dir = dataset_dir / "labels" / "val"

        for d in [train_img_dir, val_img_dir, train_label_dir, val_label_dir]:
            d.mkdir(parents=True, exist_ok=True)

        all_images = list(Path(composite_dir).glob('*.jpg'))
        valid_images = []

        for img_path in all_images:
            label_path = img_path.with_suffix('.txt')
            if label_path.exists():
                with open(label_path, 'r') as f:
                    if f.read().strip():
                        valid_images.append(img_path)

        print(f"Found {len(valid_images)} images with valid annotations")

        if len(valid_images) == 0:
            print("ERROR: No valid images found!")
            return None

        random.shuffle(valid_images)
        split_idx = int(len(valid_images) * train_ratio)
        train_images = valid_images[:split_idx]
        val_images = valid_images[split_idx:]

        for img_path in train_images:
            shutil.copy(img_path, train_img_dir / img_path.name)
            lbl_path = img_path.with_suffix('.txt')
            if lbl_path.exists():
                shutil.copy(lbl_path, train_label_dir / lbl_path.name)

        for img_path in val_images:
            shutil.copy(img_path, val_img_dir / img_path.name)
            lbl_path = img_path.with_suffix('.txt')
            if lbl_path.exists():
                shutil.copy(lbl_path, val_label_dir / lbl_path.name)

        print(f"Train: {len(train_images)}, Val: {len(val_images)}")
        return dataset_dir

    # =========================================================================
    # STEP 5: Data Augmentation
    # =========================================================================
    def step5_augment_dataset(self, dataset_dir, augmentation_factor=1):
        """Apply data augmentation to training set"""
        print(f"\nStep 5: Augmenting dataset (factor={augmentation_factor})")

        train_img_dir = dataset_dir / "images" / "train"
        train_label_dir = dataset_dir / "labels" / "train"

        transform = A.Compose([
            A.RandomBrightnessContrast(p=0.3),
            A.HueSaturationValue(p=0.3),
            A.GaussNoise(p=0.2),
            A.Blur(blur_limit=3, p=0.2),
            # A.RandomRotate90(p=0.3),
        ], bbox_params=A.BboxParams(format='yolo', label_fields=['class_labels']))

        images = list(train_img_dir.glob('*.jpg'))
        original_count = len(images)
        successful = 0

        print(f"Augmenting {original_count} images...")

        for idx, img_path in enumerate(images):
            label_path = train_label_dir / img_path.with_suffix('.txt').name
            if not label_path.exists():
                continue

            img = cv2.imread(str(img_path))
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

            bboxes, class_labels = self._read_yolo_annotations(label_path)

            for aug_idx in range(augmentation_factor):
                try:
                    augmented = transform(image=img, bboxes=bboxes, class_labels=class_labels)

                    aug_img = augmented['image']
                    aug_bboxes = augmented['bboxes']
                    aug_labels = augmented['class_labels']

                    aug_name = f"{img_path.stem}_aug{aug_idx}.jpg"
                    aug_img_bgr = cv2.cvtColor(aug_img, cv2.COLOR_RGB2BGR)
                    cv2.imwrite(str(train_img_dir / aug_name), aug_img_bgr)

                    aug_label_name = f"{img_path.stem}_aug{aug_idx}.txt"
                    self._write_yolo_annotations(train_label_dir / aug_label_name, aug_bboxes, aug_labels)

                    successful += 1
                except Exception as e:
                    print(f"Augmentation failed for {img_path.name}: {e}")
                    continue

            if (idx + 1) % 50 == 0:
                print(f"Progress: {idx + 1}/{original_count} images processed")

        augmented_count = len(list(train_img_dir.glob('*.jpg')))
        print(f"✓ Dataset augmented: {original_count} → {augmented_count} images")
        print(f"✓ Successfully created {successful} augmented images")

        return augmented_count

    # =========================================================================
    # Helper: Read YOLO Annotations
    # =========================================================================
    def _read_yolo_annotations(self, label_path):
        """Read YOLO format annotations"""
        bboxes, class_labels = [], []
        with open(label_path, 'r') as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) == 5:
                    class_id = int(float(parts[0]))
                    bbox = [float(x) for x in parts[1:]]
                    bboxes.append(bbox)
                    class_labels.append(class_id)
        return bboxes, class_labels

    # =========================================================================
    # Helper: Write YOLO Annotations
    # =========================================================================
    def _write_yolo_annotations(self, label_path, bboxes, class_labels):
        """Write YOLO format annotations (using correct class indices)"""
        with open(label_path, 'w') as f:
            for bbox, celeb_id in zip(bboxes, class_labels):
                # Convert raw celeb ID → class index
                class_idx = self.celeb_id_to_index.get(celeb_id, celeb_id)
                f.write(f"{class_idx} {bbox[0]:.6f} {bbox[1]:.6f} {bbox[2]:.6f} {bbox[3]:.6f}\n")

    # =========================================================================
    # STEP 6: Create YAML Config + Mapping
    # =========================================================================
    def step6_create_yaml_config(self, dataset_dir, celebrity_names):
        """Create YAML configuration file for YOLOv8"""
        yaml_path = dataset_dir / "dataset.yaml"

        sorted_celeb_ids = sorted(celebrity_names.keys())
        class_names = [
            celebrity_names[cid].replace("images__", "").rstrip("_")
            for cid in sorted_celeb_ids
        ]

        actual_num_classes = len(class_names)

        config = {
            'path': str(dataset_dir.absolute()),
            'train': 'images/train',
            'val': 'images/val',
            'nc': actual_num_classes,
            'names': class_names
        }

        with open(yaml_path, 'w') as f:
            yaml.dump(config, f, default_flow_style=False)

        print(f"\nDataset config saved to {yaml_path}")
        print(f"Number of classes: {actual_num_classes}")
        print(f"Sample class names: {class_names[:5]}")

        # ✅ Mapping for annotation writing
        self.celeb_id_to_index = {cid: idx for idx, cid in enumerate(sorted_celeb_ids)}
        print(f"\nCelebrity ID to Index mapping (first 5):")
        for idx, cid in enumerate(sorted_celeb_ids[:5]):
            print(f"  Celebrity {cid} -> Class Index {idx} ({class_names[idx]})")

        return yaml_path

    def step6b_convert_labels_to_class_indices(self, dataset_dir):
        """Convert all existing label files from celeb IDs → YOLO class indices"""
        print("\nStep 6b: Converting all label files to YOLO class indices...")

        label_dirs = [
            dataset_dir / "labels" / "train",
            dataset_dir / "labels" / "val"
        ]

        total_converted = 0
        for lbl_dir in label_dirs:
            for lbl_path in lbl_dir.glob("*.txt"):
                lines_out = []
                with open(lbl_path, "r") as f:
                    for line in f:
                        parts = line.strip().split()
                        if len(parts) != 5:
                            continue
                        celeb_id = int(float(parts[0]))
                        if celeb_id not in self.celeb_id_to_index:
                            print(f"⚠️ Unknown celeb ID {celeb_id} in {lbl_path.name}, skipping.")
                            continue
                        class_idx = self.celeb_id_to_index[celeb_id]
                        parts[0] = str(class_idx)
                        lines_out.append(" ".join(parts))
                # overwrite file
                with open(lbl_path, "w") as f:
                    f.write("\n".join(lines_out))
                total_converted += 1

        print(f"✓ Converted {total_converted} label files to YOLO class indices.")


    # =========================================================================
    # STEP 7: Train YOLOv8
    # =========================================================================
    def step7_train_yolov8(self, yaml_path, epochs=30, batch_size=16):
        """Train YOLOv8 model"""
        print(f"\nTraining YOLOv8 model for {epochs} epochs...")
        model = YOLO('yolov8n.pt')

        results = model.train(
            data=str(yaml_path),
            epochs=epochs,
            imgsz=self.img_size,
            batch=batch_size,
            name='celeba_detection',
            patience=20,
            save=True,
            device=0
        )

        print("\n✓ Training completed!")
        return model, results

    # =========================================================================
    # STEP 8: Evaluate model
    # =========================================================================
    def step8_evaluate_model(self, model_path, yaml_path):
        """Evaluate trained model"""
        print("\nStep 8: Evaluating model")

        model = YOLO(model_path)
        metrics = model.val(data=str(yaml_path))

        print(f"\nmAP50: {metrics.box.map50:.4f}")
        print(f"mAP50-95: {metrics.box.map:.4f}")
        print(f"Precision: {metrics.box.mp:.4f}")
        print(f"Recall: {metrics.box.mr:.4f}")

        return metrics


# ============================================================================
# MAIN EXECUTION - RUN THE COMPLETE PIPELINE
# ============================================================================

processor = TrainCelebAYOLO(
    celeba_root=EXTRACTED_DIR,
    output_root=OUTPUT_ROOT,
    num_classes=43
)
import time

# STEP 4: Split dataset
dataset_dir = processor.step4_split_dataset(composite_dir)

# STEP 6: Create YAML + mapping
yaml_path = processor.step6_create_yaml_config(dataset_dir, celebrity_names)

# ✅ STEP 6b: Convert existing raw celeb IDs → YOLO class indices
processor.step6b_convert_labels_to_class_indices(dataset_dir)

# STEP 5: Augment dataset
augmented_count = processor.step5_augment_dataset(dataset_dir, augmentation_factor=10)

# Replace 'MyFolder' with the name of the folder you want to delete
# !rm -rf /content/drive/MyDrive/celebA/output/yolo_dataset

"""##4. Data Loading and Model Training"""

# Initialize results dictionary to prevent NameError
training_results = {}

# --- STEP 7: Train ---
model, results = processor.step7_train_yolov8(
    yaml_path=yaml_path,
    epochs=30,
    batch_size=16
)

# ✅ Dynamically locate the actual best.pt path
best_model_path = Path(results.save_dir) / 'weights' / 'best.pt'
if not best_model_path.exists():
    raise FileNotFoundError(f"best.pt not found at {best_model_path}")

print(f"\n✅ Training completed! Best model: {best_model_path}")

# --- STEP 8: Evaluate ---
metrics = processor.step8_evaluate_model(
    model_path=best_model_path,
    yaml_path=yaml_path
)

# --- STEP 9: Save model to Drive ---
save_path = Path(MODEL_SAVE_DIR)
save_path.mkdir(parents=True, exist_ok=True)
shutil.copy(best_model_path, save_path / f'celeba_{n_celebs}_best.pt')

# --- STEP 10: Save results ---
training_results[n_celebs] = {
    'model_path': str(save_path / f'celeba_{n_celebs}_best.pt'),
    'augmented_images': augmented_count,
    'mAP50': float(metrics.box.map50),
    'mAP50-95': float(metrics.box.map),
    'precision': float(metrics.box.mp),
    'recall': float(metrics.box.mr)
}

print(f"\n✓ Configuration {n_celebs} celebs completed!")

# --- STEP 11: Plot train/val loss curves ---
results_csv = Path(results.save_dir) / 'results.csv'
if results_csv.exists():
    df = pd.read_csv(results_csv)
    plt.figure(figsize=(10, 6))
    plt.plot(df['epoch'], df['train/box_loss'], label='Train Box Loss')
    plt.plot(df['epoch'], df['val/box_loss'], label='Val Box Loss')
    plt.plot(df['epoch'], df['metrics/mAP50(B)'], label='mAP50 (B)')
    plt.xlabel('Epoch')
    plt.ylabel('Loss / mAP')
    plt.title('Training and Validation Loss Curves')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(Path(results.save_dir) / 'train_val_curves.png')
    plt.close()
    print(f"📉 Saved training curves to {results.save_dir}/train_val_curves.png")
else:
    print("⚠️ No results.csv found to plot loss curves.")

# --- STEP 12: Export per-class metrics as CSV ---
val_dir = Path(results.save_dir).parent / 'val'
metrics_txt = val_dir / 'results.txt'

# Alternative way — directly extract from YOLO model
yolo_model = YOLO(best_model_path)
val_results = yolo_model.val(data=yaml_path, split='val', save_json=True)

# Create a DataFrame for per-class metrics
num_classes_with_metrics = len(val_results.box.p)
all_class_names = list(val_results.names.values())

per_class_data = []

for i in range(num_classes_with_metrics):
    class_name = all_class_names[i] if i < len(all_class_names) else f"Class_{i}"
    per_class_data.append({
        'class_id': i,
        'class_name': class_name,
        'precision': float(val_results.box.p[i]),
        'recall': float(val_results.box.r[i]),
        'mAP50': float(val_results.box.ap50[i]),
        'mAP50-95': float(val_results.box.ap[i])
    })

# Add placeholder rows for classes with no metrics
if len(all_class_names) > num_classes_with_metrics:
    for j in range(num_classes_with_metrics, len(all_class_names)):
        per_class_data.append({
            'class_id': j,
            'class_name': all_class_names[j],
            'precision': 0.0,
            'recall': 0.0,
            'mAP50': 0.0,
            'mAP50-95': 0.0
        })

df_metrics = pd.DataFrame(per_class_data)
df_metrics.loc[len(df_metrics)] = {
    'class_id': 'ALL',
    'class_name': 'Overall',
    'precision': val_results.box.mp,
    'recall': val_results.box.mr,
    'mAP50': val_results.box.map50,
    'mAP50-95': val_results.box.map
}

csv_path = Path(results.save_dir) / 'classwise_metrics.csv'
df_metrics.to_csv(csv_path, index=False)
print(f"📊 Saved classwise metrics to {csv_path}")

# --- STEP 13: Print summary ---
print("\n" + "="*70)
print("TRAINING RESULTS SUMMARY")
print("="*70)

for n_celebs, res in training_results.items():
    print(f"\n{'─'*70}")
    print(f"Configuration: {n_celebs} Celebrities per Image")
    print(f"{'─'*70}")
    print(f"Model saved to: {res['model_path']}")
    print(f"Augmented images: {res['augmented_images']}")
    print(f"mAP50: {res['mAP50']:.4f}")
    print(f"mAP50-95: {res['mAP50-95']:.4f}")
    print(f"Precision: {res['precision']:.4f}")
    print(f"Recall: {res['recall']:.4f}")

print("\n" + "="*70)
print("✓ ALL STEPS COMPLETED SUCCESSFULLY!")
print("✓ Models and metrics saved to Google Drive")
print("="*70)

"""##5. Performance Metrics

###
1. Training/Validation Curves
2. Accuracy, Precision, Recall, F1 Score
3. Ascending Order of Precion for each class (CF)
"""



"""##6. Inference"""

from google.colab.patches import cv2_imshow
# Path to test image
TEST_IMAGE = '/content/drive/MyDrive/celebA/output/yolo_dataset/images/val/composite_00001.jpg'

# Run inference
print("Running inference...")
results = model.predict(
    source=TEST_IMAGE,
    conf=0.01,  # Confidence threshold
    save=True
)

# Get the annotated image
annotated_img = results[0].plot()  # Draw boxes on image

# Display the image in Colab
print("\n✓ Inference complete! Displaying result:\n")
cv2_imshow(annotated_img)

# Print detections
print("\n" + "="*60)
print("DETECTED CELEBRITIES:")
print("="*60)

boxes = results[0].boxes
if len(boxes) == 0:
    print("No celebrities detected!")
else:
    for i, box in enumerate(boxes):
        class_id = int(box.cls[0])
        confidence = float(box.conf[0])
        bbox = box.xyxy[0].cpu().numpy()  # [x1, y1, x2, y2]

        print(f"\nCelebrity #{i+1}:")
        print(f"  - ID: {class_id}")
        print(f"  - Confidence: {confidence:.2%}")
        print(f"  - Location: ({int(bbox[0])}, {int(bbox[1])}) to ({int(bbox[2])}, {int(bbox[3])})")

print("\n" + "="*60)
print(f"Total celebrities detected: {len(boxes)}")
print("="*60)

# Also save the result
output_path = '/content/drive/MyDrive/inference_result.jpg'
cv2.imwrite(output_path, annotated_img)
print(f"\n✓ Result saved to: {output_path}")

